version: "3.8"

services:
  app:
    build:
      context: ./minila
      args:
        TZ: Asia/Tokyo
        NGINX_HOST: myapp
        NGINX_PORT: 80
        NGINX_DOCROOT: /var/approot/myapp/public/
    container_name: myapp
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:10czCaBujOG8k0AwnV4KF/NT1jp0mhswdWlQS3muLDA=
      - APP_DEBUG=true
      - APP_URL=http://myapp:8000
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mydb
      - DB_PORT=3306
      - DB_DATABASE=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
      - CACHE_DRIVER=redis
      - FILESYSTEM_DRIVER=local
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - REDIS_HOST=mycache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=hoge
      - MAIL_PASSWORD=hoge
      - MAIL_ENCRYPTION=null
      # - MAIL_FROM_ADDRESS=null
    command: start.sh
    volumes:
      - approot:/var/approot
    ports:
      - 8000:80
      - 9003:9003 # xdebug
    tty: true

  db:
    build: ./mysql
    container_name: mydb
    volumes:
      - mydb:/var/lib/mysql
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydbuser
      - MYSQL_PASSWORD=mydbpass
    expose:
      - 3306
    ports:
      - 3306:3306

  mail:
    image: mailhog/mailhog:latest
    container_name: mailhog
    environment:
      - TZ=Asia/Tokyo
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis:alpine
    container_name: mycache
    environment:
      - TZ=Asia/Tokyo
    expose:
      - 6379
    ports:
      - 6379:6379


  # log:
  #   image: fluentd:latest
  #   container_name: mylog

volumes:
  approot:
    driver: local
  mydb:
    driver: local
